// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class adduser_permissionsx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduser_permissionsx));
        
        string IMigrationMetadata.Id
        {
            get { return "201312142311318_adduser_permissionsx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
