// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class action_update_to_decimal_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(action_update_to_decimal_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201404090252574_action_update_to_decimal_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
