// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class userprofile_permission1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofile_permission1));
        
        string IMigrationMetadata.Id
        {
            get { return "201408051259060_userprofile_permission1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
