// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class log4net : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(log4net));
        
        string IMigrationMetadata.Id
        {
            get { return "201412262026526_log4net"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
