// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class add_foreign_key_customerdomain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_foreign_key_customerdomain));
        
        string IMigrationMetadata.Id
        {
            get { return "201404262117374_add_foreign_key_customerdomain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
