// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class click_cookies__conversionLog_campaignid_customerid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(click_cookies__conversionLog_campaignid_customerid));
        
        string IMigrationMetadata.Id
        {
            get { return "201408022107403_click_cookies__conversionLog_campaignid_customerid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
