// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Block_endIp_index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Block_endIp_index));
        
        string IMigrationMetadata.Id
        {
            get { return "201412261851528_Block_endIp_index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
