// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class ticker_all_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticker_all_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201405070452538_ticker_all_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
