// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class url_nulleable_revenue_cost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(url_nulleable_revenue_cost));
        
        string IMigrationMetadata.Id
        {
            get { return "201411092215573_url_nulleable_revenue_cost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
