// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class remove_Profilepic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_Profilepic));
        
        string IMigrationMetadata.Id
        {
            get { return "201504280335316_remove_Profilepic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
