// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Impression_subids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Impression_subids));
        
        string IMigrationMetadata.Id
        {
            get { return "201501101830113_Impression_subids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
