// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class field_Optimization_no_truncates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(field_Optimization_no_truncates));
        
        string IMigrationMetadata.Id
        {
            get { return "201601060701402_field_Optimization_no_truncates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
