// <auto-generated />
namespace CpaTicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_InlineSubIds_RemoveCollectionFromClick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_InlineSubIds_RemoveCollectionFromClick));
        
        string IMigrationMetadata.Id
        {
            get { return "201604260818008_Add_InlineSubIds_RemoveCollectionFromClick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
